#!/bin/sh
# postinst script for hudson
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    configure)

    	/etc/init.d/tomcat7 stop

    	# remove deployed webapp from tomcat, just to be sure
		if [ -d /var/lib/tomcat7/webapps/projectdb ]; then
			rm -rf /var/lib/tomcat7/webapps/projectdb
		fi

		# adjust permissions
		if [ ! -d /var/lib/projectdb/ ]; then
			mkdir -p /var/lib/projectdb/
		fi
		chown -R tomcat7:tomcat7 /var/lib/projectdb


		# create log dir
		if [ ! -d /var/log/projectdb ]; then
			mkdir /var/log/projectdb
			chown -R tomcat7:tomcat7 /var/log/projectdb
		fi

		/etc/init.d/tomcat7 start
	;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;

esac
